export const GET_SINGLE_EXPERIENCE = 'GET_SINGLE_EXPERIENCE';
export const GET_EXPERIENCES = 'GET_EXPERIENCES';

export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_BY_CAREER_ID = 'GET_PROJECTS_BY_CAREER_ID';

export const GET_SINGLE_BLOG = 'GET_SINGLE_BLOG';
export const GET_BLOG = 'GET_BLOG';
