// GENERATED by scripts/optimize-images.ts - do not edit
//
// The "blog" images: each original URL (exactly as it appears in the
// content data) mapped to its optimized AVIF/WebP variants, so <Picture>
// can render a zero-CLS <picture> with real width/height.
// Re-run `bun run images` to regenerate.

import type { OptimizedImage } from '../../types/images.ts'

export const IMAGES: Record<string, OptimizedImage> = {
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/vietnam-768x576.jpg": {
    "width": 768,
    "height": 576,
    "avif": [
      {
        "src": "/img/2018-08-vietnam-768x576-ad836a6d-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-vietnam-768x576-ad836a6d-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-vietnam-768x576-ad836a6d-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-vietnam-768x576-ad836a6d-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-vietnam-768x576-ad836a6d-480.webp",
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAQBQCdASoYABIAPu1urlIppiQiqAgBMB2JQBidP/wDgprnqZX3oXImTwFMeuD1MigAAP6b3JgzB5wHPbXSWgAoObd2rrzVBB8dbKR4M16BgvXFDEMR0eVoP1yX1awzGFWZewSRD3cXOYyzEeld07cUiSVYmVZs+kZbfedqm3MJ0lWCzA7VuI8oYxbKHdNgHUAPBw+KcmmtpTk35CHcVjuEuuA8gAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/17-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-17-768x432-d4d22149-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-17-768x432-d4d22149-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-17-768x432-d4d22149-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-17-768x432-d4d22149-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-17-768x432-d4d22149-480.webp",
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JagCdMoMjbDMaOWF5OlqlfnmBLOIAAP7ZXJNdMrrZs4NSbHg0sNDVIkSDxSqT9RAwm7IDqDVuBqCWyUbjpQLMGqJOJbU1Zypgyxq3jeY9mJnvkH5HmlY3tNjKmLRV3bdN6kG9Q+KPKwAjxOSXQIAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/16-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-16-768x432-86b65088-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-16-768x432-86b65088-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-16-768x432-86b65088-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-16-768x432-86b65088-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-16-768x432-86b65088-480.webp",
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JagCdAB3e/dC8FJHZibtJTygAAPzZXQJ70MROjBJf93NHWWFqABwOfyy7y9ssDvD8Z9lKPaCKo0SJY0nqK25SGWID569a2rORXJZtM24rTF/b5pwh3RshxKoxu7Tf0wTa8u3mM2i5N3j/hN8DnedGuILpzGYNaXw8RshUzmkqAAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/15-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-15-768x432-2415f51f-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-15-768x432-2415f51f-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-15-768x432-2415f51f-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-15-768x432-2415f51f-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-15-768x432-2415f51f-480.webp",
    "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdL1AVieUslpuEoBF1AAD2GFRN3umjvG3/5b1VmTbraZASzvSGjKf48ED9SBQDhhvBaGZhLZ8PMxnBSzkXIgSRXDaJmsPXNypRu56xQOcaD9cuN+NHNl0CeFW2s/D1XzP2HLmmcTOpr3NHJ90cPpJj9vlIpn/pQH6IBjJrRlfKZxOcnB2ugGMilR9qPyyLJYINd8NmxzT5AAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/14-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-14-768x432-7b2ed6dd-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-14-768x432-7b2ed6dd-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-14-768x432-7b2ed6dd-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-14-768x432-7b2ed6dd-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-14-768x432-7b2ed6dd-480.webp",
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdkBtcAA2FlZEz6qXco7vysAAD7pYeK91bY9S7kJ+ingGD+mPy4sjUAUFs7M9VfmGCUkSnwnIccnINzu28J4qTEr/cagaxOOmIA9V2S/UI57cH/m+yJtY9YF7JxyqNGEtxTU070rblxmJugtotFFQPdovAwoVzkIFHW10srfy4sRUasgl+wq5ElblOCUgRcAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/13-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-13-768x432-e8d75c6f-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-13-768x432-e8d75c6f-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-13-768x432-e8d75c6f-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-13-768x432-e8d75c6f-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-13-768x432-e8d75c6f-480.webp",
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQDG9YuG3KoR+4SP90xOqyVAAP7TUzHaMBJkjoGt1amupewqmttMxFSXinqgCftNcA7tT7AaBL4yv+9goajNeUA6T9T5uBusoX1gXdLIWG1aV0S0oGoSRvigdTFtNe5fY/af/lM5apiz3Lta7WX2AAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/12-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-12-768x432-f19173ca-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-12-768x432-f19173ca-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-12-768x432-f19173ca-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-12-768x432-f19173ca-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-12-768x432-f19173ca-480.webp",
    "lqip": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAAAQBQCdASoYAA4APu1iqU2ppaOiMAgBMB2JZACpFE02VSI/FL9iehxG16cveHDfQoFgAP4+ABaMa9pXzRJ6wN+uEfhHZUwXsEB+ouHN7oE2CmTNXHIeFX3MV8+csMj9RksJAdhQ4Fl6ug04Fz91WOcF+e+d63AuIUwI6a7OL3jOihKwuVBftyq+HvgPkMsPj8vWBNpK5fc9A7ddsJfnE2vnXCAL0Ykac5y3wfP9jT02rr/0Q45AtSiOBVSmw66Ae8t4jQAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/11-440x330.jpg": {
    "width": 440,
    "height": 330,
    "avif": [
      {
        "src": "/img/2018-08-11-440x330-7cb84133-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-11-440x330-7cb84133-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/2018-08-11-440x330-7cb84133-200.webp",
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACwBACdASoYABIAPu1qrFEppaQiqAqpMB2JYwC7AAorA8wrihuKIc+qjcPsCucAAP5pqoFdoePlrQhR4n8ooF7YUOA9iWyIuKw0LQl7tYVMBkTuS31mQOKZes+KyQNckE2Tv4bbSvqRiw8sNhm5FTX0umjBBjX23dJ50wFJpA2Y/BOQajOdK7kDcXB0xO/+1ux345+K4oqHvBb+PEsKZqrUzkZkF5PH7mEDVGuFNBuvAAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/10-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-10-768x432-e83d51ac-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-10-768x432-e83d51ac-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-10-768x432-e83d51ac-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-10-768x432-e83d51ac-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-10-768x432-e83d51ac-480.webp",
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JaACdMoMljE5Pp/KhB47NKoL9YbewAP27rBD4i1HzKIbZR3OBTqUnZwSCOYGiDqmjD/LL6b8qzVhwWnpM8e/hY3n04wSqzdoG0fQpCTBlcRDT0GyNTb23xkdwDdlst2LMZ2/FBjsiKY+rt5gzAS19sBPvLRh4d2DY1ZOyiDhazAinTvFXOQTm8TEY9FKhApLo68Q3GHRigAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/9-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-9-768x432-a3dffa37-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-9-768x432-a3dffa37-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-9-768x432-a3dffa37-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-9-768x432-a3dffa37-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-9-768x432-a3dffa37-480.webp",
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwDA3CFsjj79wkiyvdq/aS4AAP7okhhT6plOURwxIZdloqDqEqCVvcpmzWQeFf09dm38UnpJqo5+9BTWbrax5QA0rSSN8XRXbPGs0sO7L/WzIB0JN2xSBS3oNfWvcEvKwPM5Mrj1fjxr4zi8KV7riJr91r5aAAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/8-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-8-768x432-00df950f-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-8-768x432-00df950f-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-8-768x432-00df950f-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-8-768x432-00df950f-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-8-768x432-00df950f-480.webp",
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZwAD5SoMg4Y6uaRwdPiMLGSAAN5XnYpFXbmGNFh+8XXrxBUsyx1tZ7smW1ypSryT8r4VeQ0ILvANH5UZ4bFcRDlwvFP++Zsf4Xrjzz2Wanfu0mmOEpDt4ytnQiHnqK5+gEsakqyJM4kJvjdbm0mBhZPK9RkU61/lz7LMnD49n1qNB3AAAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/7-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-7-768x432-610c73d3-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-7-768x432-610c73d3-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-7-768x432-610c73d3-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-7-768x432-610c73d3-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-7-768x432-610c73d3-480.webp",
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQDImCHEar1rY35r8AyQAP7yngY5M95kREwXpvYcLdtm7EG260pjLk46qJZqbPpanboNlm50nBKUP9HPqSHSCeJryGr2g6+eMWKwAAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/6-768x576.jpg": {
    "width": 768,
    "height": 576,
    "avif": [
      {
        "src": "/img/2018-08-6-768x576-264b3238-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-6-768x576-264b3238-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-6-768x576-264b3238-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-6-768x576-264b3238-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-6-768x576-264b3238-480.webp",
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAwBQCdASoYABIAPu1ur1IppiQiqAgBMB2JZQDH6agAjt4MinTzLiI4febTVurARtP9AAD8+wCvZhYSAod2ava7v6A+/U6/ayff8LTpoDNfltnrjT7nZZUkEt4uusB4znmox843kdinILNuSyng56nPZRii6xbWqvKR95qjS43eFECI2iDvlnUhqKl+/WBNBEoC25T0/4EU5FNQC8l0Gu52JQF49sWIeYjDQ+ywAAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/5-768x576.jpg": {
    "width": 768,
    "height": 576,
    "avif": [
      {
        "src": "/img/2018-08-5-768x576-98fdc319-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-5-768x576-98fdc319-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-5-768x576-98fdc319-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-5-768x576-98fdc319-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-5-768x576-98fdc319-480.webp",
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBQCdASoYABIAPu1irFAppSQisBgIATAdiUAYmwI/Q0zKXeTC0JVXT8Ppdpvt9lCYAP7rYP1+1GmdUMwL42re+umuOhCHoQ//4TeJ0xe0ovy5lUg33AoM+k6XcmRIClDwWxbT1foB6X5ex7+pXnmEaIBGPeNTMs3DFfwLob3gn0vDshlTrwJv0k6gvYm6hqajq5rBxAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/4-440x330.jpg": {
    "width": 440,
    "height": 330,
    "avif": [
      {
        "src": "/img/2018-08-4-440x330-4c6b7940-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-4-440x330-4c6b7940-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/2018-08-4-440x330-4c6b7940-200.webp",
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAAAwBQCdASoYABIAPu1srVEppaQiqAqpMB2JaAC+SBCwWh+MlEqfwcVPlVb2EQ2mTvGB+AD+8Gwn3c+phQKpQqEVxwc3Xr9Dsv++4ptxP0iOIYtxqWLCcZcVpXLiqSpOd/wWiSq8nXceNe2id75xP6rKhQYL947Kv+jHBefXd4wiEglh7wjz8X5w7R81/EwBxuvHj/g8ZF5PKnu+OVgCu1M5rKYYpgk62lUNjyBdIXsFSAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/3-768x576.jpg": {
    "width": 768,
    "height": 576,
    "avif": [
      {
        "src": "/img/2018-08-3-768x576-16b11cdb-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-3-768x576-16b11cdb-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-3-768x576-16b11cdb-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-3-768x576-16b11cdb-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-3-768x576-16b11cdb-480.webp",
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoYABIAPu1gqU2ppSQiMBgMATAdiWMAyLjQQYv9cs6wZnAR3xrBrK2rBwrqLvAAAP7b1yvKDVDmkxkDesjLHLcjAtRLz/rcqro6Jt/7Ew2GOnoRxeSq+dlqqZrpowH/V+sfQ+0cFZu2A2Gpuz4eDALGoGnf7x6ACijLTuKPNm0DkwAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/2-768x432.jpg": {
    "width": 768,
    "height": 432,
    "avif": [
      {
        "src": "/img/2018-08-2-768x432-034b2548-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-2-768x432-034b2548-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-2-768x432-034b2548-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-2-768x432-034b2548-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-2-768x432-034b2548-480.webp",
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoMh3NAB6TikUOrkYt4XFAAA/hnHgY/qJvktILSyGkNn7TExmJDaH3ppVF7t0dkbh0aYFWV1B98UP6UAwTqBT1CTeHryeWtKuW/It6RbBA1DzeP+8T3SrSxEldfYDHeuubrkyZGv104idKr1ceKL8kqsxtGXsRZh+AET3CXGJHnVKN9e5RQR2PklNIjTqbrM8r7kAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/18-440x330.jpg": {
    "width": 440,
    "height": 330,
    "avif": [
      {
        "src": "/img/2018-08-18-440x330-4e1a27cc-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-18-440x330-4e1a27cc-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/2018-08-18-440x330-4e1a27cc-200.webp",
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAAAwBQCdASoYABIAPu1wsFIppiSiqAgBMB2JZQDDrYyKdFsNmhCfYB8HLJri1HJXUFy5wADOM1JsNAKNsqVM+azPmqTUR4+1DV5fCqH4i+MyOgzryzD5xclNJOmqjJAWr4XgdRUhVxMA8LjJ1BR08Ddj8ORyuLXlcWItj0+IXzSCUc/zFip/V69Xsd31fjF7ooln/U9NlbNP9ux3pOi2qlED7GoIvM1U32gkAAAA"
  }
}
