// GENERATED by scripts/optimize-images.ts - do not edit
//
// The "career" images: each original URL (exactly as it appears in the
// content data) mapped to its optimized AVIF/WebP variants, so <Picture>
// can render a zero-CLS <picture> with real width/height.
// Re-run `bun run images` to regenerate.

import type { OptimizedImage } from '../../types/images.ts'

export const IMAGES: Record<string, OptimizedImage> = {
  "https://www.stable.xyz/images/identity/stable-wordmark.svg": {
    "width": 933,
    "height": 240,
    "avif": [],
    "webp": [],
    "fallback": "/img/images-identity-stable-wordmark-56d13636.svg",
    "lqip": "",
    "svg": "/img/images-identity-stable-wordmark-56d13636.svg"
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/genopets/genopets.png": {
    "width": 1600,
    "height": 986,
    "avif": [
      {
        "src": "/img/images-genopets-genopets-9f2907bb-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-960.avif",
        "w": 960
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/images-genopets-genopets-9f2907bb-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-960.webp",
        "w": 960
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/images-genopets-genopets-9f2907bb-1600.webp",
    "lqip": "data:image/webp;base64,UklGRjICAABXRUJQVlA4WAoAAAAQAAAAFwAADgAAQUxQSBABAAABgGPb2rHnPu8b27Zt27ZtV7ZtG5WdVBmCXf8zSf993z+FiFDbtg3jMjr1CwhJgHGYuxKIII+aAR5KRqG2DHKk5OoeqgG4+nkbQwRGDCYBZvA2Avx0FD09FcGJCeN+6oCGh72XOQiuJiAAuv1ny3auaiMn+zl+fv1dapUOQM3JdXTezXAi81TwKhyKBbv+rzmOhtF5eNl8fXHtV5U7Vm4fK6w8rv+er6vIcQnO+9H7GfdNTti4We5Nz/0auHiO1DR7zJ7Y1Wjbbbf04CY7Mtn705G5VZurMfJ2ZhzEsby4vOiUSGLiGBhXgKlbWbStHuChreTlqQjOOQmfYtjsGC6+szS5omagvL9I/jHIVQliA1ZQOCD8AAAAEAUAnQEqGAAPAD7tYqlNqaWjojAIATAdiWwAnTKEdyaBiAG8RftH6O5M0A46J9EoAADxMLiVszOVYxhik33jTDjrAJ4hDEqsNTWHEEJQtVtiAoB/tDJuS6TkPu3iCoq1QxM7rs6X+0ySBSJWSRBbvf/OWeNAd5v4c40eKMVzxZ8ybuSb4q8z/D/YmZSa03ZrOPx+EiGvE4enshI/hutOdez38qqiqMxfYVQn70pg6FX/u1j3MxP49aOsMoCuV/uLgI2fWX0982kiZQ/7/+6Tz/umX42otXzsHv+wmvnv+MC3/Y+P/a/W/4uvPWfQ6gP6fh/eV/wZnv+J4AAA"
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/genopets/genopets-banner.png": {
    "width": 1200,
    "height": 630,
    "avif": [
      {
        "src": "/img/images-genopets-genopets-banner-710cee66-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-banner-710cee66-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-banner-710cee66-960.avif",
        "w": 960
      }
    ],
    "webp": [
      {
        "src": "/img/images-genopets-genopets-banner-710cee66-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-banner-710cee66-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-banner-710cee66-960.webp",
        "w": 960
      }
    ],
    "fallback": "/img/images-genopets-genopets-banner-710cee66-960.webp",
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAwCdASoYAA0APu1iqk4ppaQiMAgBMB2JYwCsACHe1CM9mmAAAP7r1P3OwBrED1VMoL/x+HJdNTmh6F1ReK+1yVAAAA=="
  },
  "https://www.dashify.com.au/wp-content/themes/dashify/images/logo.png": {
    "width": 400,
    "height": 100,
    "avif": [
      {
        "src": "/img/dashify-images-logo-3b7e92de-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/dashify-images-logo-3b7e92de-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/dashify-images-logo-3b7e92de-200.webp",
    "lqip": "data:image/webp;base64,UklGRgIBAABXRUJQVlA4WAoAAAAQAAAAFwAABQAAQUxQSJEAAAAAA0ldVRkAAQAAAQAAAAABAwAAAAAAAgAABGhxebUnH4A4H2ARYEU7Fkk6UV9WHUsCDXg6AEeCW4qLi8pfwU6hgayJtpJtwm4AEKuvgll9XIObtqp3eL+jgKyMplAMtxkAEKumtsMkHX5LNxNSYUk5FkY8PwgBQAgABCsoMh4AAQAAAQEAAAABAwAAAQMBAQAAAFZQOCBKAAAAMAMAnQEqGAAGAD7tYqlNqaWjojAIATAdiUAACUhk5UN8AADvj+p1XfKk6G4AFZbOg3xDEvv/l2sM7unSdx/+782O9nwSRLwRwAA="
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/dashify/dashify-banner.png": {
    "width": 1656,
    "height": 1052,
    "avif": [
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-960.avif",
        "w": 960
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-960.webp",
        "w": 960
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/images-dashify-dashify-banner-ef0a503d-1600.webp",
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoYAA8APu1kqU2ppaOiMAgBMB2JZACdIMgDAO3nKVYqlGJagAD+3+mkiVPWtAI00kSSM8FAEpvdvMGf9pDarUB8BcwD9Squ+4wk9SgrUqyAD1jlMPYCh9oGjv8fN0Q7d1tIGABLuUE/x77bhqbsKUTxCyAAAA=="
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/zookal/zookal.png": {
    "width": 750,
    "height": 225,
    "avif": [
      {
        "src": "/img/images-zookal-zookal-c783b4ba-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-zookal-zookal-c783b4ba-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/images-zookal-zookal-c783b4ba-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-zookal-zookal-c783b4ba-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/images-zookal-zookal-c783b4ba-480.webp",
    "lqip": "data:image/webp;base64,UklGRo4BAABXRUJQVlA4WAoAAAAQAAAAFwAABgAAQUxQSKEAAAABgGLb2rLl3vd3d7f8D+BP/gORRHNoLs3d3ZpLcnd3yCyGAI0BaHLmEBGJfyQFSYLELxEvyFDLVQqZDDIphYoyIREAzE+fn6mlD8NTG9GluarRTMNdfksQAmmfr5/9utWB9uyPwsrnl1j658paCALW+8/3cNPjwMluw9H6TH33/Nj+5XEUhGM0Dn8wYA/A65FI9CZqdHYVQAIECAiAJCQEAABWUDggxgAAANAFAJ0BKhgABwA+7WKpTamlpCIwCAEwHYlsAJ0yhHA3oH4q1IFCwfpnrGY5MBtdebJnBs+I/AAA/o2wUTsOKDVzqp5hhlSTuHW+TOaNh72QEylZTMSYmXKCQiWJkZMip0dJm//7TL9uRiSNO57koALpWH+hv9VObo0oPnsGBl6nSjGl9N+TWk8/VpozNr4+tf6X9rzB+BuKuv4CVCKYPj+FqKv5Xc9qpexf+sl4Uz/N/ATFT37TD92PIRL/6cPiL/VgUAAAAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/ceomag-logo-1-768x286.png": {
    "width": 768,
    "height": 286,
    "avif": [
      {
        "src": "/img/2018-08-ceomag-logo-1-768x286-02ecf12c-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-ceomag-logo-1-768x286-02ecf12c-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-ceomag-logo-1-768x286-02ecf12c-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-ceomag-logo-1-768x286-02ecf12c-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-ceomag-logo-1-768x286-02ecf12c-480.webp",
    "lqip": "data:image/webp;base64,UklGRkYBAABXRUJQVlA4WAoAAAAQAAAAFwAACAAAQUxQSM8AAAABgGPb2rHnfGZs23Z+M5VtozaqVGxTp84cnNS2MYtMJiKC+Y1qx0Yg63Ewa3WVtEWHa6sYURAWThEITfPsRW6yT3rB+56EwF8/qqjY8p0jpZXuT9WK1ta8Vozx34CIjPwwsLnH8hW1AX+Kwx1yfA+ioEZLd07dQ8enJpvaQRDdmD63oWeKnwCESw6nofNSQ4CWiYySybLso+FYz75tTpTmjcUiCoKSkF5VGRVZkJ5RVZyRnhhTXJ1oAki56YnZaanx6bEpSZmpyQmpmdmRCAAAVlA4IFAAAABwAwCdASoYAAkAPu1kqU2ppaQiMAgBMB2JZACdAC0H4kBwDAAA/u/GjHV4SF0fiiAkNjBmO0+AKdVCXWV03DQLZKFjfXCjahcwdheiLXqQAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/tpf-logo-440x265.png": {
    "width": 440,
    "height": 265,
    "avif": [
      {
        "src": "/img/2018-08-tpf-logo-440x265-bd6712e9-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-tpf-logo-440x265-bd6712e9-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/2018-08-tpf-logo-440x265-bd6712e9-200.webp",
    "lqip": "data:image/webp;base64,UklGRiQCAABXRUJQVlA4WAoAAAAQAAAAFwAADQAAQUxQSDUBAAABkHRb27G3uq/niZORnZlt27Zt28bMtu3Utm2M7HZku3cdERNgvP7ow8cn223AAcYY4wx//UhE9OMHFYP/gX/raZvr6eqq1VMkkFqRlJeuBwYGbB2QnN2wuqgw+1QCXtVFyStu4Ayc0R3Vl/SF0vPIF2ZxETkJOmCQFBSkm0rPNjZVSm+hWqzcaMwtmHJA0YPRNLqt8tLBMH4LUSvOZu7Y1nTAA5dDzjrTbaVXDhvo/dMveTgdtGV7/T53XDU7aklvd3y12HYkMCFBCmdedLS17PPCNevjlt9+EJlvu9W7VgqcjUBzyx53XDc/bk3fPv8w23KptUEKOOeMtrbtJ1JXd19WOkpE5tuvZKuAwVMBRkb2pf6Oi/FqwhErZw0KY8Dwnywnp+8AAzgD/sIZOOcCQjGF/fMAVlA4IMgAAAAwBQCdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoMYPYCZAN5AIjMYGewarVifXGTmAAD+lQjLjOa6jSQTzLL5/4UinXcesrpKAyP6MUt5fROtmS+5NlTW4aVqQH8bF4Jy5IO+P9zI/W6WAnyfdxxJ4JC0lrr6rdX67oNy3j2ED0husT+876J163PiokgAcbFBm9eVAw9F1N8toTvSELJE79i6p7+zl7vjCm8dbs+LL9JjIvUx5y1mpDj9Fxdr4jSDwFvrY0AAAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/kforce-logo.png": {
    "width": 427,
    "height": 99,
    "avif": [
      {
        "src": "/img/2018-08-kforce-logo-53325a26-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-kforce-logo-53325a26-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/2018-08-kforce-logo-53325a26-200.webp",
    "lqip": "data:image/webp;base64,UklGRhoBAABXRUJQVlA4WAoAAAAQAAAAFwAABQAAQUxQSIwAAAABgCPbtmlrPTuzbb/ctm372zYjo8G/ERGRrwPZm/Z3VdN0djOJz22HpDeaTJ6GyVbFzcWdQHPFws28abs85IGd7nO4+dcZ8FSY3wHdu9Mt/ytoiF9mWMPgdI4nPvVPiUVzNhg86qEstaGsxwgTw8QMXcWjc/fYDWs6EIgMoubGcNK3gUggAASAAAL+A1ZQOCBoAAAAUAMAnQEqGAAGAD7tYqlNqaWjojAIATAdiWQAnQAOqQtJhgAA/ujvSYIGStnB+pGfre/eXK8YZYOIzUGz5WYVL6tb7658lWVTQSoT5O8wb608a5/oYh7Arf5jxriMIjnYE1qCzi4AAAA="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/iserve-logo.png": {
    "width": 192,
    "height": 70,
    "avif": [
      {
        "src": "/img/2018-08-iserve-logo-ed71fe5b-192.avif",
        "w": 192
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-iserve-logo-ed71fe5b-192.webp",
        "w": 192
      }
    ],
    "fallback": "/img/2018-08-iserve-logo-ed71fe5b-192.webp",
    "lqip": "data:image/webp;base64,UklGRoQBAABXRUJQVlA4WAoAAAAQAAAAFwAACAAAQUxQSLQAAAABgLJt2/lX9f08z9+2t6VFJtt930PN6LYaI5NttMUt7Vdn24yIBEHr1+M/jLa3PogIk4gIM7EIA1pv85tSAMZPJgDQ918ePr5N5oXHx3iz8hJy4mICkRn5qaSOmHgriMLY+b3SdT2wdqZcD2287dYBgbtJMEYurm5Hn1bG3g7q37aVu0qg9CEbagzPbE2WHe3vDS4U7hYNP8yqYLSpABi1Jq3KbtFrDRq9Wusw4ScTEb4zAQBWUDggqgAAALAEAJ0BKhgACQA+7WKqTamlpCIwCAEwHYlmAKj1ixWYAPkhVij9i+GsVNodnwAA/sdqAQtjs2x0aWI3Qb4qSUjrUpJ3M3EWVYDa8wctWKwwYAWZ9/+5/0Y1ofN2SVRHvW07q5qd+CmIX/ULlBgqs65LRO8ZdUg+h37us4c2ZeLmuX4EsOTrOfWW27p9YnQgq2kr6f6qpooiUKquBVlr+ufFVRSS9kCwAAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/yondu-logo-768x162.png": {
    "width": 768,
    "height": 162,
    "avif": [
      {
        "src": "/img/2018-08-yondu-logo-768x162-801d9dfc-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-yondu-logo-768x162-801d9dfc-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-yondu-logo-768x162-801d9dfc-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-yondu-logo-768x162-801d9dfc-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-yondu-logo-768x162-801d9dfc-480.webp",
    "lqip": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4WAoAAAAQAAAAFwAABAAAQUxQSHkAAAAAvZUZ31Wl+/NkMfR5BNBW1ObUOFe/AJSUPePWnYDjJ2TrbvnuPt1m6FKW2H3RAKemAIj5ELCcAA7ZnMquy9tj4xcc4JzIAKKlAGHbAHD1W5XjaNwn4/te64DCyFTwYN6EAEaZAgOD1sk+K6cAWLg/qMShIwCG3aUTAFZQOCAwAAAAsAIAnQEqGAAFAD7tYqlNqaWjojAIATAdiWcAAHsgAP7aSdJz0C75FPJe90UGHngA"
  }
}
