// GENERATED by scripts/optimize-images.ts - do not edit
//
// The "projects" images: each original URL (exactly as it appears in the
// content data) mapped to its optimized AVIF/WebP variants, so <Picture>
// can render a zero-CLS <picture> with real width/height.
// Re-run `bun run images` to regenerate.

import type { OptimizedImage } from '../../types/images.ts'

export const IMAGES: Record<string, OptimizedImage> = {
  "https://www.stable.xyz/images/identity/stable-wordmark.svg": {
    "width": 933,
    "height": 240,
    "avif": [],
    "webp": [],
    "fallback": "/img/images-identity-stable-wordmark-56d13636.svg",
    "lqip": "",
    "svg": "/img/images-identity-stable-wordmark-56d13636.svg"
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/genopets/genopets.png": {
    "width": 1600,
    "height": 986,
    "avif": [
      {
        "src": "/img/images-genopets-genopets-9f2907bb-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-960.avif",
        "w": 960
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/images-genopets-genopets-9f2907bb-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-960.webp",
        "w": 960
      },
      {
        "src": "/img/images-genopets-genopets-9f2907bb-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/images-genopets-genopets-9f2907bb-1600.webp",
    "lqip": "data:image/webp;base64,UklGRjICAABXRUJQVlA4WAoAAAAQAAAAFwAADgAAQUxQSBABAAABgGPb2rHnPu8b27Zt27ZtV7ZtG5WdVBmCXf8zSf993z+FiFDbtg3jMjr1CwhJgHGYuxKIII+aAR5KRqG2DHKk5OoeqgG4+nkbQwRGDCYBZvA2Avx0FD09FcGJCeN+6oCGh72XOQiuJiAAuv1ny3auaiMn+zl+fv1dapUOQM3JdXTezXAi81TwKhyKBbv+rzmOhtF5eNl8fXHtV5U7Vm4fK6w8rv+er6vIcQnO+9H7GfdNTti4We5Nz/0auHiO1DR7zJ7Y1Wjbbbf04CY7Mtn705G5VZurMfJ2ZhzEsby4vOiUSGLiGBhXgKlbWbStHuChreTlqQjOOQmfYtjsGC6+szS5omagvL9I/jHIVQliA1ZQOCD8AAAAEAUAnQEqGAAPAD7tYqlNqaWjojAIATAdiWwAnTKEdyaBiAG8RftH6O5M0A46J9EoAADxMLiVszOVYxhik33jTDjrAJ4hDEqsNTWHEEJQtVtiAoB/tDJuS6TkPu3iCoq1QxM7rs6X+0ySBSJWSRBbvf/OWeNAd5v4c40eKMVzxZ8ybuSb4q8z/D/YmZSa03ZrOPx+EiGvE4enshI/hutOdez38qqiqMxfYVQn70pg6FX/u1j3MxP49aOsMoCuV/uLgI2fWX0982kiZQ/7/+6Tz/umX42otXzsHv+wmvnv+MC3/Y+P/a/W/4uvPWfQ6gP6fh/eV/wZnv+J4AAA"
  },
  "https://www.dashify.com.au/wp-content/themes/dashify/images/logo.png": {
    "width": 400,
    "height": 100,
    "avif": [
      {
        "src": "/img/dashify-images-logo-3b7e92de-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/dashify-images-logo-3b7e92de-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/dashify-images-logo-3b7e92de-200.webp",
    "lqip": "data:image/webp;base64,UklGRgIBAABXRUJQVlA4WAoAAAAQAAAAFwAABQAAQUxQSJEAAAAAA0ldVRkAAQAAAQAAAAABAwAAAAAAAgAABGhxebUnH4A4H2ARYEU7Fkk6UV9WHUsCDXg6AEeCW4qLi8pfwU6hgayJtpJtwm4AEKuvgll9XIObtqp3eL+jgKyMplAMtxkAEKumtsMkHX5LNxNSYUk5FkY8PwgBQAgABCsoMh4AAQAAAQEAAAABAwAAAQMBAQAAAFZQOCBKAAAAMAMAnQEqGAAGAD7tYqlNqaWjojAIATAdiUAACUhk5UN8AADvj+p1XfKk6G4AFZbOg3xDEvv/l2sM7unSdx/+782O9nwSRLwRwAA="
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/dashify/dashify-banner.png": {
    "width": 1656,
    "height": 1052,
    "avif": [
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-960.avif",
        "w": 960
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-960.webp",
        "w": 960
      },
      {
        "src": "/img/images-dashify-dashify-banner-ef0a503d-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/images-dashify-dashify-banner-ef0a503d-1600.webp",
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoYAA8APu1kqU2ppaOiMAgBMB2JZACdIMgDAO3nKVYqlGJagAD+3+mkiVPWtAI00kSSM8FAEpvdvMGf9pDarUB8BcwD9Squ+4wk9SgrUqyAD1jlMPYCh9oGjv8fN0Q7d1tIGABLuUE/x77bhqbsKUTxCyAAAA=="
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/zookal/zookal.png": {
    "width": 750,
    "height": 225,
    "avif": [
      {
        "src": "/img/images-zookal-zookal-c783b4ba-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-zookal-zookal-c783b4ba-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/images-zookal-zookal-c783b4ba-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-zookal-zookal-c783b4ba-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/images-zookal-zookal-c783b4ba-480.webp",
    "lqip": "data:image/webp;base64,UklGRo4BAABXRUJQVlA4WAoAAAAQAAAAFwAABgAAQUxQSKEAAAABgGLb2rLl3vd3d7f8D+BP/gORRHNoLs3d3ZpLcnd3yCyGAI0BaHLmEBGJfyQFSYLELxEvyFDLVQqZDDIphYoyIREAzE+fn6mlD8NTG9GluarRTMNdfksQAmmfr5/9utWB9uyPwsrnl1j658paCALW+8/3cNPjwMluw9H6TH33/Nj+5XEUhGM0Dn8wYA/A65FI9CZqdHYVQAIECAiAJCQEAABWUDggxgAAANAFAJ0BKhgABwA+7WKpTamlpCIwCAEwHYlsAJ0yhHA3oH4q1IFCwfpnrGY5MBtdebJnBs+I/AAA/o2wUTsOKDVzqp5hhlSTuHW+TOaNh72QEylZTMSYmXKCQiWJkZMip0dJm//7TL9uRiSNO57koALpWH+hv9VObo0oPnsGBl6nSjGl9N+TWk8/VpozNr4+tf6X9rzB+BuKuv4CVCKYPj+FqKv5Xc9qpexf+sl4Uz/N/ATFT37TD92PIRL/6cPiL/VgUAAAAA=="
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/genopets/genopets-banner-v2.png": {
    "width": 2388,
    "height": 1230,
    "avif": [
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-960.avif",
        "w": 960
      },
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-960.webp",
        "w": 960
      },
      {
        "src": "/img/images-genopets-genopets-banner-v2-48697e2b-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/images-genopets-genopets-banner-v2-48697e2b-1600.webp",
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBACdASoYAAwAPu1kqU2ppaQiMAgBMB2JagCdMoADY9e4bw7k9PcfV0gAAP7jhX5tCkZde4qUzjmA7wKTQtlGSoEeEP/Pc3FZETPvsiSDyK/Am3WJk5FwAHelGp6HQLGoffzYTsYf1OyJKQr7hAOBvERzHexjUjsvNp8f2zTXusA2bElyBIDEz1bzPLj310xb2tXvdO3OUnDa0mREKs9KtY3AAA=="
  },
  "https://felixstatic.s3.ap-southeast-2.amazonaws.com/uploads/images/zookal/zookal1.png": {
    "width": 1500,
    "height": 1113,
    "avif": [
      {
        "src": "/img/images-zookal-zookal1-df439ee7-200.avif",
        "w": 200
      },
      {
        "src": "/img/images-zookal-zookal1-df439ee7-480.avif",
        "w": 480
      },
      {
        "src": "/img/images-zookal-zookal1-df439ee7-960.avif",
        "w": 960
      }
    ],
    "webp": [
      {
        "src": "/img/images-zookal-zookal1-df439ee7-200.webp",
        "w": 200
      },
      {
        "src": "/img/images-zookal-zookal1-df439ee7-480.webp",
        "w": 480
      },
      {
        "src": "/img/images-zookal-zookal1-df439ee7-960.webp",
        "w": 960
      }
    ],
    "fallback": "/img/images-zookal-zookal1-df439ee7-960.webp",
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwBACdASoYABIAPu1sq1GppaOiqAqpMB2JZQDL4BEcyn5mglBzo8pfq1FtZC0QAP6wJ2gNHi5+8oQtTY5AeZgQ2+yzNx1QC8pLQp17SDzHPJJHvojZXBSZx1DG3Vl2R795xHRtmp0yG2uiiPOJ5vPCC7oJyR5sMSpTlrRNi/DvhIAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/Screen-Shot-2018-08-14-at-3.04.44-PM-768x668.png": {
    "width": 768,
    "height": 668,
    "avif": [
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-04-44-pm-768x668-b4b8add8-200.avif",
        "w": 200
      },
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-04-44-pm-768x668-b4b8add8-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-04-44-pm-768x668-b4b8add8-200.webp",
        "w": 200
      },
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-04-44-pm-768x668-b4b8add8-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/18-08-screen-shot-2018-08-14-at-3-04-44-pm-768x668-b4b8add8-480.webp",
    "lqip": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAAAwBQCdASoYABUAPu1ur1IppiQiqAgBMB2JZwDNhywYbwYjzTHzTSw9if/nq2IioLmk4AD+1itVifKYgTnHx2nzYKRR2dz2I430spTSN9HjSASh+f1OT4SA9/oVzPm8wJWZJNyz0kYqIfs3tIW5YV+gE5SQgfsR1V1UTc85PDoJP3y0PY54RGC9VXpejte6x7blf8wmIaHmR3p1oXqHrlLF5Ko+61I43PXPXJCiQl0l5dOLSbDskPv3Yg1/nT98Z8NKrTw0Kz+BEAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/Screen-Shot-2018-08-14-at-2.56.45-PM-768x530.png": {
    "width": 768,
    "height": 530,
    "avif": [
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-2-56-45-pm-768x530-a73c72b6-200.avif",
        "w": 200
      },
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-2-56-45-pm-768x530-a73c72b6-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-2-56-45-pm-768x530-a73c72b6-200.webp",
        "w": 200
      },
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-2-56-45-pm-768x530-a73c72b6-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/18-08-screen-shot-2018-08-14-at-2-56-45-pm-768x530-a73c72b6-480.webp",
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACwBACdASoYABEAPu1gp04ppSMiMBgMATAdiWMAtsgPR6vNyjJx3GM2Gg66aQeQAP7GB5K5JnMSdcGeZs4s85bEf916xrNqbV53aXx+nZBlI4LHWTp7PIt1earswscbxppyQ9ncUkY4KkcceydZHwtYdadmlZe0fA+2/BUomrq2tWd6694MZA3uE6wTUHN8kQAXqSQ+D0E9bo495r2h5z0MXaxzjCvFRyvWsAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/Screen-Shot-2018-08-14-at-3.02.48-PM-768x600.png": {
    "width": 768,
    "height": 600,
    "avif": [
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-02-48-pm-768x600-c385d55e-200.avif",
        "w": 200
      },
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-02-48-pm-768x600-c385d55e-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-02-48-pm-768x600-c385d55e-200.webp",
        "w": 200
      },
      {
        "src": "/img/18-08-screen-shot-2018-08-14-at-3-02-48-pm-768x600-c385d55e-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/18-08-screen-shot-2018-08-14-at-3-02-48-pm-768x600-c385d55e-480.webp",
    "lqip": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAADQBQCdASoYABMAPu1ur1KppiQiqAgBMB2JZQDIfNkRfivgX+uPs6hUutvEEKO+rqIfzUdi72YQAP6yP6NHOFi8YKw3emVtr2k6mmQZ1Uoa/ataOn8SdrGbLTwBvxblj5Vg2cLKvWncA1x1/0RGMlPa0AbapMH3+XNtAdFApNpLdIwv8zBilU9zIgGRAq6AAKC78U1Yyhiq2/piDnJxotzu9nTHQ1pAp+2swt1vyqpwCwEaCGU8q/sG2UNW2m+YeNbBCiY0SjgR9Omw5OS55d/i9ElEqmPQAu5QAAAA"
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/acs7-440x314.jpeg": {
    "width": 440,
    "height": 314,
    "avif": [
      {
        "src": "/img/2018-08-acs7-440x314-f96548a7-200.avif",
        "w": 200
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-acs7-440x314-f96548a7-200.webp",
        "w": 200
      }
    ],
    "fallback": "/img/2018-08-acs7-440x314-f96548a7-200.webp",
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADQBACdASoYABEAPu1ur1IppiQiqAgBMB2JZgCdMuI6ABkR8SDB2nBLuBD1rLw4AAD3z1ZN2xOlITpZLha0jt8eCATQbJ1TBJknVcZ52hi3EIciBOs8OhGaR0/t+M7YAc5GSIjuoTuq3eOBiZ2lQTNKHdlih1ssWnEP8Y5znr9ba4mklclkkE2g8I+nWZP1RchEMU7qb2jSruvOTnl+YITjX4NRdNg1FoAAAA=="
  },
  "https://felixstatic.s3.amazonaws.com/uploads/2018/08/hmi1-768x354.png": {
    "width": 768,
    "height": 354,
    "avif": [
      {
        "src": "/img/2018-08-hmi1-768x354-cb069467-200.avif",
        "w": 200
      },
      {
        "src": "/img/2018-08-hmi1-768x354-cb069467-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/2018-08-hmi1-768x354-cb069467-200.webp",
        "w": 200
      },
      {
        "src": "/img/2018-08-hmi1-768x354-cb069467-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/2018-08-hmi1-768x354-cb069467-480.webp",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoYAAsAPu1kqk4ppaQiMAgBMB2JYwAAW6XKVKX0eYTgAAD+XviGhJyNKocFwl//0HxlbeEK6AwacAXOiKqNMC0rNr5OscuTcFAAAA=="
  }
}
