// GENERATED by scripts/optimize-images.ts - do not edit
//
// The "site" images: each original URL (exactly as it appears in the
// content data) mapped to its optimized AVIF/WebP variants, so <Picture>
// can render a zero-CLS <picture> with real width/height.
// Re-run `bun run images` to regenerate.

import type { OptimizedImage } from '../../types/images.ts'

export const IMAGES: Record<string, OptimizedImage> = {
  "https://images.unsplash.com/photo-1649061267116-bf9d813b3757?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaWdpdGFsJTIwbm9tYWQlMjBsYXB0b3AlMjBjYWZlfGVufDF8fHx8MTc2NTMyNTcwNHww&ixlib=rb-4.1.0&q=80&w=1600": {
    "width": 1600,
    "height": 1600,
    "avif": [
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-480.avif",
        "w": 480
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-960.avif",
        "w": 960
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-480.webp",
        "w": 480
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-960.webp",
        "w": 960
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/photo-1649061267116-bf9d813b3757-4fea0c8f-1600.webp",
    "lqip": "data:image/webp;base64,UklGRh4BAABXRUJQVlA4IBIBAADwBQCdASoYABgAPu1srlIppaQiqAgBMB2JQBYhn+uAIoMJQ46pj3Bt0MWZewBkllUKpRPOz0qtAADyoz+h+j2SYR/Y+Ap4A/7kx+xM5k85XjwF/sAMuTiMMIDQ/3Uq4VB1ubW1smeSbqCXeqJa5e6M+5J3uXtkuYHg3MZxZqmwvidEOR7EP4lQvd+Evq6VrsTifJaqV1YRu3fGB7zqEA1kr1lL3TL7ViiHlT+BbhUfBfPYwBdu8BtAVVz5sej0MAlbxtiavbWz7Omvuhcq1HB7m3pyZy8/PrflnAsqgw5TcaLsmKfwvt6aF7IZkDlNTdmo0AqNXNmEntiRedshGB7QWxMFlxDcnbUF4EqA7MywxwAA"
  },
  "https://images.unsplash.com/photo-1609765685592-703a97c877ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhaXJwbGFuZSUyMHdpbmRvdyUyMHRyYXZlbHxlbnwxfHx8fDE3NjUzMDE2MTF8MA&ixlib=rb-4.1.0&q=80&w=1600": {
    "width": 1600,
    "height": 2133,
    "avif": [
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-480.avif",
        "w": 480
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-960.avif",
        "w": 960
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-480.webp",
        "w": 480
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-960.webp",
        "w": 960
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf799409-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/photo-1609765685592-703a97c877ba-cf799409-1600.webp",
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwBACdASoYACAAPu1qqVAppiOiqA1RMB2JZwDNwEXhjQj/NiaqRtMvIKoX+eTLdiAA/vd8vMj/psmK2tcvhYWt7RM5cyjn41P+ftyXzJYE3s8yxVKgAkp/WwCLjLDRlOOeaV2wOX967UeX9dvRj0yaRdUzuuGLT9zuyttHgJR9+Bg8GXe4ZExo583txoFXhWKAAA=="
  },
  "https://images.unsplash.com/photo-1652793822328-47340b1b4407?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaXR5JTIwd2Fsa2luZyUyMHN0cmVldHxlbnwxfHx8fDE3NjUzMjU3MDR8MA&ixlib=rb-4.1.0&q=80&w=1600": {
    "width": 1600,
    "height": 2400,
    "avif": [
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-480.avif",
        "w": 480
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-960.avif",
        "w": 960
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-480.webp",
        "w": 480
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-960.webp",
        "w": 960
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/photo-1652793822328-47340b1b4407-3d3dcfc9-1600.webp",
    "lqip": "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAAAQBwCdASoYACQAPu1qrFCppaQiqqgBMB2JQBgFgTk9QLoDbz4UhpvNAUIHyPa8NLVqQceMEKgxLzaH/WWxc0KFSAD+zYRb5N4DOkyFS22RpDaayg76Te0kiiCMFEIbLzI90PggdasAjjoGCMUeYudD3o8JYUqbpkZtOtFdcQdPbJxktX153PiC7Wdo7JI4WmxsDn2DfLJLujvfeECtiXQWsOeFeh4KsgsgNZRdgaN4c7z+e+erZ7Ser27qLxW9mYiUd3/N2ZHSKY+IPZRZKzjMeL5vAZw3MiF6ZlLqnZnrlkl3q33ediMppRrAR0axMmWa7k1xcGEWgjIvwAA="
  },
  "https://images.unsplash.com/photo-1758767055219-35755e2d76bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXQlMjBmb29kJTIwY3VsdHVyZXxlbnwxfHx8fDE3NjUzMjU3MDR8MA&ixlib=rb-4.1.0&q=80&w=1600": {
    "width": 1600,
    "height": 2845,
    "avif": [
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-480.avif",
        "w": 480
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-960.avif",
        "w": 960
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-1600.avif",
        "w": 1600
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-480.webp",
        "w": 480
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-960.webp",
        "w": 960
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-1600.webp",
        "w": 1600
      }
    ],
    "fallback": "/img/photo-1758767055219-35755e2d76bf-e74f0efd-1600.webp",
    "lqip": "data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAAAQCACdASoYACsAPu1uqlAppqOiqrgMATAdiWIAuzLrw7Z/1Lq9AhXB565AdbFi3prW4nAs8UH0JPhRxfBOo6VfSBAvlduu/RoAAPimYUNTKxV2nhKQD9J5WVCD2dw5OPVyPJmJ0hD72ueFkIsmlLa0tvk5kDonZXRg86gRuegRT7XMNT8Ij1gRPXMkPS1uazDKLRFsSXtMpYoOholXYHyJZY1yrsTXN8VWgnXb3XDd8Qb6nXplGwmrjh0HX3G2xjXMm748qo5S9XcL4J7lR+mKOehgvN/8XwMzPY2MZbzMh9L+YcPROp/a2sSNBAr1JNmj0ebVTJjZuSpX5F1onY+Ta/XI9AB/6RlHZhi5oDkHf4si4SaGPSDK/tPLiedrS+hf9KqrZZjfMAAA"
  }
}
