// GENERATED by scripts/optimize-images.ts - do not edit
//
// The "site" images: each original URL (exactly as it appears in the
// content data) mapped to its optimized AVIF/WebP variants, so <Picture>
// can render a zero-CLS <picture> with real width/height.
// Re-run `bun run images` to regenerate.

import type { OptimizedImage } from '../../types/images.ts'

export const IMAGES: Record<string, OptimizedImage> = {
  "https://images.unsplash.com/photo-1649061267116-bf9d813b3757?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=640": {
    "width": 640,
    "height": 640,
    "avif": [
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-9bb17117-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-9bb17117-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-9bb17117-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1649061267116-bf9d813b3757-9bb17117-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/photo-1649061267116-bf9d813b3757-9bb17117-480.webp",
    "lqip": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAAAwBgCdASoYABgAPu1srlIppaQiqAgBMB2JQBYhnQ+kOKxYCaAdcMWK5rTuuRnxFuo+H+Ym0oQBM8sAAOu+XTPjywYTcgKJd6twVa+N1NyYBPjrFKrz4IzUbrb7T+EDXFarBghNcDjsf5PfTmfH0Vuqvtu4LpQcOHXs9AYHu4w8KVRdzZoCrv4wdkY192iS+330RU4Ktd2wCnRWdTgPJ5Vkh5OEhWp0WvP+XoNskY/QCt3egvsA7W7iJZsn9qqyoamIeJKuqDIvfcZqvWd7YCya3ozqd7azRRz2BJ7UTEiRcA8ZaeD4aTht1ems/QsPokbA0CqtL46/GQI9YFn6mhAzGxETi1ovwt5CdB9ArvI1qDn0LYyDE1oAAAA="
  },
  "https://images.unsplash.com/photo-1609765685592-703a97c877ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=640": {
    "width": 640,
    "height": 853,
    "avif": [
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf4dcd34-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf4dcd34-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf4dcd34-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1609765685592-703a97c877ba-cf4dcd34-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/photo-1609765685592-703a97c877ba-cf4dcd34-480.webp",
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQBACdASoYACAAPu1ur1IppiQiqAgBMB2JZwDBzFbSzc/QuewymjQgGzInVfAwAAD++RO6CELr3BdegF+4ATtqCwQDO/ywzSJNSPVcfpwkgIO3S73NLToJdTHCRLuBnh/RyxpShYA4axRzBhM9rTTnOk53Y5i6pnfC9aW8zoHHMjYXPN9UkBmb1oE/UCR0AAA="
  },
  "https://images.unsplash.com/photo-1652793822328-47340b1b4407?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=640": {
    "width": 640,
    "height": 960,
    "avif": [
      {
        "src": "/img/photo-1652793822328-47340b1b4407-d345fd88-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-d345fd88-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1652793822328-47340b1b4407-d345fd88-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1652793822328-47340b1b4407-d345fd88-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/photo-1652793822328-47340b1b4407-d345fd88-480.webp",
    "lqip": "data:image/webp;base64,UklGRhABAABXRUJQVlA4IAQBAACQBgCdASoYACQAPu1srVCppiQiqqgBMB2JQBZaATwVJ1BonYNVYeiS2faEzb2z07jezLoRdtJtTM/r4VQAAP7NhFvk3iSZ57Y+1Pup5tNbZ5GQNIf2eRNxz/OoXNGSvpeU/QJqaHXdodcGNV9IXdwX9fOoBdtIXqEhDeQMyyvT8aqYE7NKzhjPpcgcwAF/Y0P6tKPcShXv19p7hoSfz9XsJmgPYMF7AGu8lNIiytdpmYVSQ9pp57QBiyWrs6bMYsqfNHYgByt1MBwBV/BFaC0SfMqwwvS9jWBgynOEn6ExNP/XMoqnzzDCjQ/l6v+WcG9BeHAvfdl2agiryoWXfCDva4AAAA=="
  },
  "https://images.unsplash.com/photo-1758767055219-35755e2d76bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=640": {
    "width": 640,
    "height": 1138,
    "avif": [
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-eee4b2f6-200.avif",
        "w": 200
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-eee4b2f6-480.avif",
        "w": 480
      }
    ],
    "webp": [
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-eee4b2f6-200.webp",
        "w": 200
      },
      {
        "src": "/img/photo-1758767055219-35755e2d76bf-eee4b2f6-480.webp",
        "w": 480
      }
    ],
    "fallback": "/img/photo-1758767055219-35755e2d76bf-eee4b2f6-480.webp",
    "lqip": "data:image/webp;base64,UklGRkIBAABXRUJQVlA4IDYBAADwBgCdASoYACsAPu1oqk6ppiOiKqwBMB2JYgCdMymBtCJBtj2SOEmQfGwALspicRz/cRPfRE5ZpKOYX4lI4sGAAPimZG+AEUWKbaynAjh/wwRWd4xq1DCG5E/nB9HlByEgrDrHnWkPDQBG1Dd4nHb+hWDx8oL4p82hPX+31J5DajnxlD4tdu/RTaDgRvDWv5AGA0UfVI8tWKwNIvCByIPZmtOc/wc1x14Nj0RfDQ80T7csZ48Q7Ric3uchlKCDZkOt6nOiIAu6OxYqSWQ6HlBTgo38R6OyVW035gUZwugmKEhDEAhWchFAn53qn+p2y70kF4vebuLW5X7CRxJ6Ohp2zclSvyLoDhclhva1Hue/syo5ivppOpP5Np27JTiyTcwZPRLGGU30E6jOTg7sDZEn0J6pwAAA"
  }
}
