/**
 * One-off transform: splits src/data/blog.ts (full post bodies) into:
 *  - src/data/blog-index.ts           BlogPostMeta[] - every field except
 *                                      `content`, same order. Small enough
 *                                      to ship on every page.
 *  - src/data/blog-content/<slug>.ts  one file per post, `content` only -
 *                                      each becomes its own chunk, loaded
 *                                      only by /blog/:slug.
 *
 * src/data/blog.ts stays the hand-maintained source of truth; re-run this
 * whenever it changes.
 *
 * Run: bun scripts/split-blog.ts  (also `bun run blog:split`)
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { blogPosts } from '../src/data/blog.ts'

const DATA_DIR = path.resolve(import.meta.dir, '../src/data')
const CONTENT_DIR = path.join(DATA_DIR, 'blog-content')

const HEADER = '// GENERATED by scripts/split-blog.ts from src/data/blog.ts - do not edit\n'

mkdirSync(CONTENT_DIR, { recursive: true })

const blogIndex = blogPosts.map(({ content, ...meta }) => meta)

writeFileSync(
  path.join(DATA_DIR, 'blog-index.ts'),
  HEADER +
    `import type { BlogPostMeta } from '../types/data'\n\n` +
    `export const blogIndex: BlogPostMeta[] = ${JSON.stringify(blogIndex, null, 2)}\n`,
)

for (const post of blogPosts) {
  writeFileSync(
    path.join(CONTENT_DIR, `${post.slug}.ts`),
    HEADER + `export const content = ${JSON.stringify(post.content)}\n`,
  )
}

console.log(`Wrote blog-index.ts (${blogIndex.length} posts) and blog-content/ (${blogPosts.length} files)`)
