// GENERATED by scripts/split-blog.ts from src/data/blog.ts - do not edit
import type { BlogPostMeta } from '../types/data'

export const blogIndex: BlogPostMeta[] = [
  {
    "slug": "5-things-to-do-in-ho-chi-minh-city-vietnam",
    "title": "5 Things to do in Ho Chi Minh City, Vietnam",
    "excerpt": "Ho Chi Minh is the capital city of Vietnam, there are a lot of things you can do here but you can squeeze your time and do amazing things in just few days!",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/vietnam-768x576.jpg",
      "alt": "5 Things to do in Ho Chi Minh City, Vietnam",
      "width": 768,
      "height": 576
    },
    "publishedDate": "2018-08-22T09:56:39",
    "modifiedDate": "2018-08-23T10:02:27",
    "tags": []
  },
  {
    "slug": "first-skydiving-experience",
    "title": "First Skydiving Experience",
    "excerpt": "I want to do something daring and what could it possibly be other than the adrenaline rush and heart-stopping skydiving",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/17-768x432.jpg",
      "alt": "First Skydiving Experience",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:18:05",
    "modifiedDate": "2018-08-23T10:06:32",
    "tags": []
  },
  {
    "slug": "4d-3n-itinerary-phuket-thailand",
    "title": "4D 3N Itinerary Phuket, Thailand",
    "excerpt": "Phuket is a small famous island in Thailand and known for its limestone caves, blue waters, beautiful sandy beaches, magnificent islands, food &amp; night life.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/16-768x432.jpg",
      "alt": "4D 3N Itinerary Phuket, Thailand",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:17:10",
    "modifiedDate": "2018-08-23T10:06:12",
    "tags": []
  },
  {
    "slug": "the-3-best-tonkotsu-ramen-to-try-in-fukuoka-japan-yatai-ippudo-ramen-street",
    "title": "The 3 Best Tonkotsu Ramen to try in Fukuoka, Japan &#8211; Yatai, Ippudo, Ramen Street",
    "excerpt": "Some people consider this if not the best, definitely one of the best ramen there is",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/15-768x432.jpg",
      "alt": "The 3 Best Tonkotsu Ramen to try in Fukuoka, Japan &#8211; Yatai, Ippudo, Ramen Street",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:16:17",
    "modifiedDate": "2018-08-26T10:45:41",
    "tags": []
  },
  {
    "slug": "1d-itinerary-in-fukuoka-japan-nanzoin-temple-yatai-ippudo",
    "title": "1D Itinerary in Fukuoka, Japan &#8211; Nanzoin Temple, Yatai, Ippudo",
    "excerpt": "Some people consider this if not the best, definitely one of the best ramen there is",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/14-768x432.jpg",
      "alt": "1D Itinerary in Fukuoka, Japan &#8211; Nanzoin Temple, Yatai, Ippudo",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:15:39",
    "modifiedDate": "2018-08-26T10:46:47",
    "tags": []
  },
  {
    "slug": "itinerary-in-osaka-dotonbori-osaka-castle-shinsekai",
    "title": "Itinerary in Osaka &#8211; Dotonbori, Osaka Castle, Shinsekai",
    "excerpt": "We just arrived in Osaka City.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/13-768x432.jpg",
      "alt": "Itinerary in Osaka &#8211; Dotonbori, Osaka Castle, Shinsekai",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:14:57",
    "modifiedDate": "2018-08-26T10:57:16",
    "tags": []
  },
  {
    "slug": "osaka-dotonbori-non-stop-eating",
    "title": "Osaka Dotonbori &#8211; Non stop eating",
    "excerpt": "Dotonbori is a famous shopping and food street in Osaka. A must when you go here!",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/12-768x432.jpg",
      "alt": "Osaka Dotonbori &#8211; Non stop eating",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:13:53",
    "modifiedDate": "2018-08-26T10:46:25",
    "tags": []
  },
  {
    "slug": "where-to-stay-in-japan-tokyo-osaka-kyoto-fukuoka",
    "title": "Where to stay in Japan &#8211; Tokyo, Osaka, Kyoto, Fukuoka",
    "excerpt": "Fukuoka City &#8211; Kyusu Region&#8217;s largest and busiest city. Home of the original Tonkotsu Ramen. Home of the largest Reclining Buddha in the world.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/11-440x330.jpg",
      "alt": "Where to stay in Japan &#8211; Tokyo, Osaka, Kyoto, Fukuoka",
      "width": 440,
      "height": 330
    },
    "publishedDate": "2018-08-22T10:12:49",
    "modifiedDate": "2018-08-26T10:47:18",
    "tags": []
  },
  {
    "slug": "itinerary-in-kyoto-golden-temple-bamboo-forest-fushimi-inari-shrine",
    "title": "Itinerary in Kyoto &#8211; Golden Temple, Bamboo Forest, Fushimi Inari Shrine",
    "excerpt": "Before heading to Kyoto, I was feeling hungry and went to the street mall close to our accommodation.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/10-768x432.jpg",
      "alt": "Itinerary in Kyoto &#8211; Golden Temple, Bamboo Forest, Fushimi Inari Shrine",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:11:50",
    "modifiedDate": "2018-08-26T10:56:52",
    "tags": []
  },
  {
    "slug": "itinerary-in-tokyo-senso-ji-temple-meiji-shrine-tsukiji-market-ueno-park-shinjuku-shibuya-ramen-street-ichiran",
    "title": "Itinerary in Tokyo &#8211; Senso-ji Temple, Meiji Shrine, Tsukiji Market, Ueno Park, Shinjuku, Shibuya, Ramen Street, Ichiran",
    "excerpt": "Just arrived in Tokyo by Shinkansen from Fukuoka around 7 in the evening",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/9-768x432.jpg",
      "alt": "Itinerary in Tokyo &#8211; Senso-ji Temple, Meiji Shrine, Tsukiji Market, Ueno Park, Shinjuku, Shibuya, Ramen Street, Ichiran",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:10:47",
    "modifiedDate": "2018-08-26T11:24:04",
    "tags": []
  },
  {
    "slug": "itinerary-in-taiwan-cks-memorial-hall-taipei-zoo-ximending-shilin-raohe-night-market",
    "title": "Itinerary in Taiwan &#8211; CKS Memorial Hall, Taipei Zoo, Ximending Shilin Raohe Night Market",
    "excerpt": "Taiwan is only a small country and is known for its hot springs, night market and of course, food.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/8-768x432.jpg",
      "alt": "Itinerary in Taiwan &#8211; CKS Memorial Hall, Taipei Zoo, Ximending Shilin Raohe Night Market",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:09:40",
    "modifiedDate": "2018-08-23T10:03:44",
    "tags": []
  },
  {
    "slug": "things-to-do-and-eat-in-singapore",
    "title": "Things to do &#038; eat in Singapore &#8211; Universal Studios, Merlion Park, Marina Bay, Makansutra, Lau Pa Sat, Tian Tian Hainanese",
    "excerpt": "Even though Singapore is just a small country, there are plenty of things to see, activities to do or places to eat here.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/7-768x432.jpg",
      "alt": "Things to do &#038; eat in Singapore &#8211; Universal Studios, Merlion Park, Marina Bay, Makansutra, Lau Pa Sat, Tian Tian Hainanese",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:08:35",
    "modifiedDate": "2018-08-26T10:53:21",
    "tags": []
  },
  {
    "slug": "one-day-in-kuala-lumpur-malaysia-petronas-twin-towers-batu-caves-jalan-alor-bukit-bintang",
    "title": "One day in Kuala Lumpur, Malaysia &#8211; Petronas Twin Towers, Batu Caves &#038; Jalan Alor Bukit Bintang",
    "excerpt": "Kuala Lumpur is Malaysia&#8217;s capital city and you can see and experience this beautiful city along with its famous tourists destinations just in one day!",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/6-768x576.jpg",
      "alt": "One day in Kuala Lumpur, Malaysia &#8211; Petronas Twin Towers, Batu Caves &#038; Jalan Alor Bukit Bintang",
      "width": 768,
      "height": 576
    },
    "publishedDate": "2018-08-22T10:07:17",
    "modifiedDate": "2018-08-26T10:53:46",
    "tags": []
  },
  {
    "slug": "how-i-managed-to-travel-setting-priorities-and-be-motivated",
    "title": "How I managed to travel—setting priorities and be motivated",
    "excerpt": "A lot of people think that you need a lot of money to travel. Well, that is not totally true because it depends on how you manage your travel.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/5-768x576.jpg",
      "alt": "How I managed to travel—setting priorities and be motivated",
      "width": 768,
      "height": 576
    },
    "publishedDate": "2018-08-22T10:05:53",
    "modifiedDate": "2018-08-23T10:03:09",
    "tags": []
  },
  {
    "slug": "why-travel-now-while-you-still-can",
    "title": "Why travel now while you still can",
    "excerpt": "Travelling when you&#8217;re old and when you&#8217;re still young has a lot of difference. There are plenty of things you can do while you are still young and you can&#8217;t when you grow old and starts to build a family.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/4-440x330.jpg",
      "alt": "Why travel now while you still can",
      "width": 440,
      "height": 330
    },
    "publishedDate": "2018-08-22T10:04:51",
    "modifiedDate": "2018-08-23T10:02:54",
    "tags": []
  },
  {
    "slug": "9-reasons-why-you-should-travel-solo",
    "title": "9 reasons why you should travel solo",
    "excerpt": "Travelling solo might sound lonely but to be honest, it&#8217;s not. You will actually have a lot of advantage than travelling with someone. This will also help you conquer a lot of your fear, make you a better person, and be mature.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/3-768x576.jpg",
      "alt": "9 reasons why you should travel solo",
      "width": 768,
      "height": 576
    },
    "publishedDate": "2018-08-22T10:03:22",
    "modifiedDate": "2018-08-23T10:02:41",
    "tags": []
  },
  {
    "slug": "tips-on-how-to-travel-cheap",
    "title": "Tips on how to travel cheap",
    "excerpt": "Create a list of airlines that provides cheap deals, be patient and committed on checking them as the prices changes frequently.",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/2-768x432.jpg",
      "alt": "Tips on how to travel cheap",
      "width": 768,
      "height": 432
    },
    "publishedDate": "2018-08-22T10:01:28",
    "modifiedDate": "2018-08-23T05:25:05",
    "tags": []
  },
  {
    "slug": "worlds-highest-bungee-in-macau-tower-macau",
    "title": "World&#8217;s Highest Bungee in Macau Tower, Macau",
    "excerpt": "Wondering how it feels to jump from the world&#8217;s highest bungee? feels awesome I tell you! A must do in your next trip to Macau!",
    "image": {
      "url": "https://felixstatic.s3.amazonaws.com/uploads/2018/08/18-440x330.jpg",
      "alt": "World&#8217;s Highest Bungee in Macau Tower, Macau",
      "width": 440,
      "height": 330
    },
    "publishedDate": "2018-08-22T10:18:57",
    "modifiedDate": "2018-08-26T10:44:32",
    "tags": []
  }
]
